// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXELqMHM7D8lT-0kexYu4jfqehfLNoRC0',
    appId: '1:632604677797:web:514b1eff38122bb83d1f4c',
    messagingSenderId: '632604677797',
    projectId: 'apptaxi-e641d',
    authDomain: 'apptaxi-e641d.firebaseapp.com',
    storageBucket: 'apptaxi-e641d.firebasestorage.app',
    measurementId: 'G-NRESF3C67Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkBWDtzJIC8Sl_7TzSfwVKuliMMmoTJI',
    appId: '1:632604677797:android:57076b1536f60afd3d1f4c',
    messagingSenderId: '632604677797',
    projectId: 'apptaxi-e641d',
    storageBucket: 'apptaxi-e641d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXN2NGId0zr3ANUUxjJtF9tA3P1B9TxJ0',
    appId: '1:632604677797:ios:2deb7fe326237d9e3d1f4c',
    messagingSenderId: '632604677797',
    projectId: 'apptaxi-e641d',
    storageBucket: 'apptaxi-e641d.firebasestorage.app',
    iosBundleId: 'com.apptaxis.apptaxis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXN2NGId0zr3ANUUxjJtF9tA3P1B9TxJ0',
    appId: '1:632604677797:ios:2deb7fe326237d9e3d1f4c',
    messagingSenderId: '632604677797',
    projectId: 'apptaxi-e641d',
    storageBucket: 'apptaxi-e641d.firebasestorage.app',
    iosBundleId: 'com.apptaxis.apptaxis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXELqMHM7D8lT-0kexYu4jfqehfLNoRC0',
    appId: '1:632604677797:web:1fb92982ee10663c3d1f4c',
    messagingSenderId: '632604677797',
    projectId: 'apptaxi-e641d',
    authDomain: 'apptaxi-e641d.firebaseapp.com',
    storageBucket: 'apptaxi-e641d.firebasestorage.app',
    measurementId: 'G-NDZ9N4GLPL',
  );
}
